version: '3.6'
services:
  web:
    build:
      context: web
    ports:
      - "8080:8080"
    depends_on:
      - gateway
  web-test:
    image: nginx:1.21.6
    volumes:
      - ./web/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - gateway
  api:
    build:
      context: api
  gateway:
    build:
      context: gateway
    depends_on:
      - keycloak
      - api
    ports:
      - "3030:3030"
  keycloak:
    image: jboss/keycloak:16.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/testrealm.json
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - "18080:8080"
    volumes:
      - ./keycloak/export/testrealm.json:/tmp/testrealm.json
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - key_cloak_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

volumes:
  key_cloak_mysql_data:
    driver: local